services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./src/test/resources/data:/docker-entrypoint-initdb.d"
  candidate-service:
    build: .
    image: candidate-service
    ports:
      - "8080:8080"
    environment:
      spring.data.mongodb.uri: "mongodb://candidate_user:candidate_password@mongo:27017/candidate"
    depends_on:
      - mongo