services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./src/test/resources/data:/docker-entrypoint-initdb.d
  job-service:
    build: .
    image: job-service
    ports:
      - "8080:8080"
    environment:
      spring.data.mongodb.uri: "mongodb://job_user:job_password@mongo:27017/job"
    depends_on:
      - mongo